### ISSUE TITLE
(Obscure bug) No way to remove tracks once scanned?

### ISSUE THREAD

**Issue by jphastings** [mxcl/playdar.prefpane#10]
I have an external drive with a load of songs on, traveling for Christmas I've taken this with me and allowed playdar on my laptop to scan it for festive tune playing. Now I don't know how to un-list those tracks!

If I select my laptop's music folder from the drop down the prefpane scans the tracks there (~200 tracks) but still lists the ~8000 that were available when the external drive was scanned.

Its a bit of an obscure bug, but I'm wondering if songs you remove from your HD will be removed from playdar's library?

**Comment by mxcl** [comment]
Apologies for not responding to this sooner. My inbox is insane due to Homebrew nowadays.

So partly this depends on an uncreated issue on playdar-core. As it isn't yet possible to remove tracks from the db.

playdar-core should remove tracks if they don't exist when it gets a query for them.

Also fswatcher code I wrote can notice that stuff no longer exists and tell playdar-core to remove whole dirtrees.

Still neither bug is prefpane's responsability at this time.

Of course it would be neat to be able to add removable media to playdar as it is connected wouldn't it? We can do this. It's just a lot harder than the effort is worth… still if money ever comes into the project we can consider it.

**Comment by jphastings** [comment]
Ahh, cool. I uess it'd need to be sponsorship/corporate backing of some sort, rather than just donations. Even a system where users could shuffle a particular desired feature to the top of the pile by donating towards that feature specifically probably wouldn't generate a lot! I guess playdar-as-an-income is being heavily pondered tho!
