### ISSUE TITLE
Read PLAYDAR_ETC environment variable

### ISSUE THREAD

**Issue by jwheare** [mxcl/playdar.prefpane#3]
Should look at this for the "Show config file" button since Playdar does by default.

**Comment by jwheare** [comment]
Actually I'm not sure where it's reading config from cos neither my PLAYDAR_ETC/playdar.conf nor ~/Library/Preferences/org.playdar.conf seem to be respected.

**Comment by mxcl** [comment]
I hardcoded it to ~/Library/Preferences/org.playdar.conf, but it's broken in the current build. Fixed in my checkout though.

**Comment by mxcl** [comment]
Now hardcoded to ~/Library/Preferences/org.playdar/playdar.conf

I could respect the PLAYDAR_ETC variable, however it's easier to debug people when there's only one place you point them, and also I'd need to add something to playdarctl to get the config dir so that I wouldn't need to dupe that code in the prefpane so the user can open the dir from there.

**Comment by jwheare** [comment]
Yeah this is fine. It was initially a problem cos I thought playdarctl was using it, but not the "show log" button. Fixed.
